### ISSUE TITLE
Wish there was support for custom openai node.

### ISSUE THREAD

**Issue by zjcboy** [android-com-pl/wp-ai-alt-generator#7]
I hope you can plugin support custom openai interface, currently by modifying the code way to achieve, but each update is very inconvenient.
Thanks for your help.

**Comment by rafaucau** [comment]
Do you mean a fine-tuned model?

> currently by modifying the code way to achieve

Could you provide an example?

**Comment by zjcboy** [comment]
For example, through a third-party gpt interface, as this doesn't cost much.
https://deepbricks.ai/docs

**Comment by rafaucau** [comment]
This link requires login. If your API request data structure is other than OpenAI, well, there will be no such option in this plugin, as there are probably many such APIs and it would be impossible to maintain support for all of them.

The only reasonable option would be to add a hook filter ([apply_filters()](https://developer.wordpress.org/reference/functions/apply_filters/)) to the API request in this code, so you could then modify this in your code ([add_filter()](https://developer.wordpress.org/reference/functions/add_filter/)), which would allow you to update this plugin without overwriting your code every time.

https://github.com/android-com-pl/wp-ai-alt-generator/blob/d6b55df29104e8ab05eab15ba4c77af3c4937a14/includes/AltGenerator.php#L33-L82

**Comment by zjcboy** [comment]
It would be perfect if the plugin could provide a field where you can fill in and modify the api address.

**Comment by rafaucau** [comment]
I would prefer that such an option is not available to casual users, because some custom APIs may require a different structure for the data to be sent, which will raise unnecessary questions from users if something does not work for them.

That's why in #8 I create PHP filters that will allow more advanced users to change this URL and the structure of the request data.

When I release v2.5.1, you will be able to add such a line to `functions.php` of your theme or any other place in the code over which you have control:
```php
add_filter('acpl/ai_alt_generator/api_url', fn() => 'https://your-url-here');
```

**Comment by rafaucau** [comment]
v2.5.1 released.
Here is the documentation for other hooks: https://github.com/android-com-pl/wp-ai-alt-generator?tab=readme-ov-file#for-developers
